file=open("tops2.txt","w")
file.write("This is file write operation using python.")
file.close()
print("File Written Successfully")
print("*"*60)

file=open("tops2.txt","r")
print(file.read())
file.close()
print("*"*60)

file=open("tops2.txt","a")
file.write("\nNow this file is appended.")
file.close()
print("File Appended Successfully")
print("*"*60)

file=open("tops2.txt","r")
print(file.read())
file.close()
print("*"*60)

file=open("tops3.txt","w+")
file.write("This is w+ mode for file management in python.")
print("Current Cursor Position : ",file.tell())
file.seek(10)
print(file.read())
file.close()
print("w+ mode working")
print("*"*60)
